sudo: false
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: beta
  - rust: stable
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
services:
  - couchdb
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then nvm install iojs; fi
  - pip install 'travis-cargo<0.2' --user
  - export PATH=${PATH}:$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only stable doc
after_success:
  - travis-cargo coveralls --no-sudo
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
before_deploy:
  - mkdir package/
  - bash tools/package.sh package/cloudshack-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.tar.gz
deploy:
  provider: s3
  access_key_id: AKIAJ6SIB6XJBNQL43GQ
  secret_access_key:
    secure: fDFaiqoNVYXvVYDnQwL7Pz9uLZ4jMaGArP+j3ds41WUCQgPE9qaBZH6pK/8Y2DnUAUtJ1z0F8/XDk44kufL3+SoiAxZItp5SVnCIUBEt9mKEoxG21Y1zb7BaeUWYFKb6i/o4xLg4MrZM5vXr5NInWiYc4Obcx+MJYUlqlYahPCA=
  bucket: static.cloudshack.org
  region: eu-central-1
  local-dir: package
  acl: public_read
  skip_cleanup: true
  on:
    repo: 7h0ma5/CloudShack
    all_branches: true
