sudo: false
os:
  - linux
#  - osx
language: elixir
elixir:
  - 1.4.1
otp_release:
  - 18.2.1
env:
  global:
    - MIX_ENV=prod
services:
  - couchdb
before_script:
  - curl https://cdn.cloudshack.org/dxcc.json.gz > dxcc.json.gz
before_install:
  - nvm install 6
  - nvm use 6
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile
  - (cd webapp && npm install && npm run build)
before_deploy:
  - mix release
  - mkdir package
  - cp _build/prod/rel/cloudshack/releases/*/cloudshack.tar.gz package/cloudshack-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.tar.gz
deploy:
  provider: s3
  access_key_id: AKIAJ6SIB6XJBNQL43GQ
  secret_access_key:
    secure: fDFaiqoNVYXvVYDnQwL7Pz9uLZ4jMaGArP+j3ds41WUCQgPE9qaBZH6pK/8Y2DnUAUtJ1z0F8/XDk44kufL3+SoiAxZItp5SVnCIUBEt9mKEoxG21Y1zb7BaeUWYFKb6i/o4xLg4MrZM5vXr5NInWiYc4Obcx+MJYUlqlYahPCA=
  bucket: static.cloudshack.org
  region: eu-central-1
  local-dir: package
  upload-dir: build
  acl: public_read
  skip_cleanup: true
  on:
    repo: 7h0ma5/CloudShack
    all_branches: true
